pool:
  vmImage: ubuntu-22.04

trigger:
  branches:
    include:
    - main
    - features/*
  paths:
    exclude:
    - .circleci/config.yml
    - .github/workflows/build.yml
    - .vscode/**
    - appveyor.yml
    - LICENSE
    - README.md

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK 8'
  inputs:
    packageType: sdk
    version: 8.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UseDotNet@2
  displayName: 'Install .NET SDK 7 for Endor Scan'
  inputs:
    packageType: sdk
    version: 7.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- bash: |
    dotnet restore
  displayName: 'Restoring "Cake.Tool" .NET local tool'

- bash: |
    dotnet build
  displayName: 'Build'

- bash: |
    curl https://api.endorlabs.com/download/endorlabs/latest/binaries/endorctl_linux_amd64 -o endorctl  
    chmod +x ./endorctl
    ./endorctl scan --api-key $(ENDOR_API_CREDENTIALS_KEY) --api-secret $(ENDOR_API_CREDENTIALS_SECRET) --as-default-branch=true --detached-ref-name=master -n nate-learn --exclude="(./src/ExtraLogic.*)|(.*HelloTests.*)"
  displayName: 'Endor Scan'
